#!/usr/bin/env python3
"""Mint RACK & ROLL '26 invite tokens + codenames. LOCAL ONLY.

Outputs (all gitignored — tokens never enter the public repo):
  tokens.csv   token,inviter,codename          (the master list; goes to 1P)
  seed.sql     INSERT statements for D1        (wrangler d1 execute --file)

Tokens: 10-char Crockford base32 (~50 bits) — multi-scan, single-claim is
enforced by the Worker/D1, not here. Codenames: adjective-noun, PG-13 snark,
pre-assigned so the leaderboard only ever shows server-owned slugs.

Usage: mint_tokens.py [--per-inviter 300] [--inviters sam,connor,pearl] [--out DIR]
"""
from __future__ import annotations

import argparse
import csv
import secrets
from pathlib import Path

ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"  # Crockford base32

ADJECTIVES = """velvet polite feral discount ambient corduroy suspicious humble
chrome haunted decaf turbo modest oblique caffeinated laminated sideways
brushed municipal artisanal unlicensed diplomatic crispy phantom analog
mahogany reluctant baroque understated tactical mint gilded off-brand
low-voltage dimmable load-bearing color-corrected flush-mount rack-mounted
patch-panel surge-protected""".split()

NOUNS = """forklift mayhem chandelier gasket walkie sconce badger conduit
crouton dimmer mullet gondola thermostat pelican fresco varmint pylon
biscuit monsoon parka fixture breaker keypad woofer tweeter downlight
pendant lumen ballast raceway grommet fader amplifier subwoofer soffit
valance turntable riser truss""".split()


def mint(per_inviter: int, inviters: list[str]):
    combos = [f"{a}-{n}" for a in ADJECTIVES for n in NOUNS]
    need = per_inviter * len(inviters)
    if need > len(combos):
        raise SystemExit(f"need {need} codenames, only {len(combos)} combos")
    rng = secrets.SystemRandom()
    rng.shuffle(combos)
    seen_tokens: set[str] = set()
    rows = []
    for i, inviter in enumerate(inviters):
        for j in range(per_inviter):
            while True:
                tok = "".join(secrets.choice(ALPHABET) for _ in range(10))
                if tok not in seen_tokens:
                    seen_tokens.add(tok)
                    break
            rows.append((tok, inviter, combos[i * per_inviter + j]))
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--per-inviter", type=int, default=300)
    ap.add_argument("--inviters", default="sam,connor,pearl")
    ap.add_argument("--out", default=str(Path(__file__).resolve().parents[1] / "local"))
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    gitignore = out / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text("*\n")   # belt: the whole dir ignores itself

    rows = mint(args.per_inviter, args.inviters.split(","))

    with open(out / "tokens.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["token", "inviter", "codename"])
        w.writerows(rows)

    with open(out / "seed.sql", "w") as fh:
        fh.write("-- generated by mint_tokens.py — LOCAL ONLY, never commit\n")
        for tok, inviter, codename in rows:
            fh.write("INSERT INTO tokens (token, inviter, codename) VALUES "
                     f"('{tok}', '{inviter}', '{codename}');\n")

    print(f"minted {len(rows)} tokens → {out}/tokens.csv + seed.sql")
    print("next: store tokens.csv in 1Password; wrangler d1 execute rr26 --file seed.sql")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
