#!/usr/bin/env python3
"""Mint RACK & ROLL '26 invite codes as lighting/AV/tech WORD PAIRS. LOCAL ONLY.

The code you hand out IS the codename IS the URL slug: "photon-rack" ->
rickroll.win/photon-rack -> claim -> you're @photon-rack. Memorable, sayable,
typeable, and crossable off a printed sheet even when a QR won't scan.

Trade-off (by design, Sam's call): word pairs from a known vocabulary are
human-guessable, unlike the old random tokens. Only pairs actually minted into
D1 are valid (a guessed miss = snarky 404), and the claim form is gated by
Turnstile + the kill switch — but a determined human could guess an unclaimed
minted pair. Acceptable for a trade-show game; the kill switch cleans up.

Outputs (gitignored): tokens.csv (token,inviter,codename — token == codename)
and seed.sql (INSERTs for D1).

Usage: mint_tokens.py [--per-inviter 300] [--inviters sam,connor,pearl]
"""
from __future__ import annotations

import argparse
import csv
import secrets
from pathlib import Path

# First word: quality / signal / lighting-AV-tech modifier.
FIRST = """photon lumen kelvin lux chroma gamma phase ambient analog phantom
warm cool tunable spectral infrared linear recessed flush grazing wallwash
uplit backlit keyed diffuse focused calibrated aligned quiet dimmable wireless
hardwired coax fiber gigabit latency hertz decibel matte gloss daylight halogen
neon plasma dichroic fresnel beam flood spot wash pixel scanning motorized
balanced phantom-power biamped daisy summed muted soloed gated compressed
patched terminated shielded grounded looped buffered rendered mapped zoned
scened ramped faded crossfaded strobed chased""".split()

# Second word: a piece of gear on a rack, wall, or truss.
SECOND = """rack dimmer keypad driver ballast gateway processor amplifier
subwoofer tweeter projector screen lens gobo truss conduit raceway gang relay
contactor node hub switch router patchbay matrix encoder decoder transducer
fixture sconce pendant downlight cove soffit fader console snake dongle bracket
yoke shackle clamp anchor gland ferrule connector jack plug socket panel breaker
transformer rectifier capacitor resistor diode heatsink chassis rackmount
bezel grommet standoff pigtail whip homerun backbox mudring wallplate faceplate
knob dial trimpot potentiometer""".split()


def mint(per_inviter: int, inviters: list[str]):
    combos = [f"{a}-{n}" for a in FIRST for n in SECOND]
    need = per_inviter * len(inviters)
    if need > len(combos):
        raise SystemExit(f"need {need} pairs, only {len(combos)} combos "
                         f"({len(FIRST)}x{len(SECOND)})")
    rng = secrets.SystemRandom()
    rng.shuffle(combos)
    rows = []
    i = 0
    for inviter in inviters:
        for _ in range(per_inviter):
            pair = combos[i]; i += 1
            rows.append((pair, inviter, pair))  # token == codename
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--per-inviter", type=int, default=300)
    ap.add_argument("--inviters", default="sam,connor,pearl")
    ap.add_argument("--out", default=str(Path(__file__).resolve().parents[1] / "local"))
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    if not (out / ".gitignore").exists():
        (out / ".gitignore").write_text("*\n")

    rows = mint(args.per_inviter, args.inviters.split(","))

    with open(out / "tokens.csv", "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["token", "inviter", "codename"])
        w.writerows(rows)

    with open(out / "seed.sql", "w") as fh:
        fh.write("-- generated by mint_tokens.py — LOCAL ONLY, never commit\n")
        for tok, inviter, codename in rows:
            fh.write("INSERT INTO tokens (token, inviter, codename) VALUES "
                     f"('{tok}', '{inviter}', '{codename}');\n")

    print(f"minted {len(rows)} word-pair codes ({args.per_inviter}/inviter) "
          f"from {len(FIRST)}x{len(SECOND)} space -> {out}/tokens.csv + seed.sql")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
